### ISSUE TITLE
color version？

### ISSUE THREAD

**Issue by kitor7** [shlonkin/AutomatedArt#3]
Hi. @ericheisler 
you code is so cool!
I was wondering if it's possible to make a CMYK version of this algorithm using 3 or 4 threads instead of one. It would be amazing if this is possible. Have you thought about it?

**Comment by ericheisler** [comment]
It would be possible to run multiple colors, but the result would not be what you expect. The lines of color would stretch across the image. For example, the threads that make up the lips in a face would also be part of the eyes, hair, etc. You could make one part a specific color, but that color would be scattered throughout the rest of the image as well.
A better idea would be to use white thread and apply color to the finished product where you wanted it.
